import './globals.css'

export const metadata = {
  title: 'Giffy App',
  description: 'Generated by Daiana Arena',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-gradient-to-r from-purple-400 via-pink-500 to-red-500 '>{children}</body>
    </html>
  )
}
